import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header/Header'
import Banner from '../components/Banner/Banner'
import AboutUs from '../components/AboutUs/AboutUs'
import RoadMap from '../components/RoadMap/RoadMap'
import UtilityToken from '../components/UtilityToken/UtilityToken'
import Team from '../components/Team/Team'
import Faq from '../components/Faq/Faq'
import Footer from '../components/Footer/Footer'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Travel NFT</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Banner />
			<AboutUs />
			<RoadMap />
			<UtilityToken />
			<Team />
			<Faq />
			<Footer />
		</div>
	)
}
