import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner/Banner'
import AboutUs from '../components/AboutUs/AboutUs'
import RoadMap from '../components/RoadMap/RoadMap'
import UtilityToken from '../components/UtilityToken/UtilityToken'
import Team from '../components/Team/Team'
import Faq from '../components/Faq/Faq'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<Banner />
			<AboutUs />
			<RoadMap />
			<UtilityToken />
			<Team />
			<Faq />
		</div>
	)
}
